export BROWSERSTACK_USERNAME="your_username"
export BROWSERSTACK_ACCESS_KEY="your_token"
export APP_USERNAME="dummy_username"
export APP_PASSWORD="dummy_password"
export BROWSERSTACK_BUILD_NAME="Automate Build #123"
export BROWSERSTACK_PROJECT_NAME="bs-demo-cert"
